# Generated by Django 5.0.3 on 2024-03-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_academicyear_comment_contributionfiles_contributions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='academicYear',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='contributions',
            name='academic_Year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.academicyear'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_Year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.academicyear'),
        ),
    ]
