# Generated by Django 5.0.3 on 2024-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_faculties_academicyear_academicyear_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='status',
            field=models.CharField(default='waiting', max_length=10),
        ),
    ]
