# Generated by Django 4.2.7 on 2024-03-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contributions_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
