# Generated by Django 5.0.3 on 2024-03-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contributions_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='code',
        ),
    ]
