# Generated by Django 5.0.3 on 2024-03-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_academicyear_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='academic_Year',
        ),
    ]
