# Generated by Django 5.0.3 on 2024-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_room_img_roomfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.AddField(
            model_name='pageview',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
