# Generated by Django 5.0.3 on 2024-04-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_pageview_page_name_remove_pageview_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activities_count',
            field=models.IntegerField(default=0),
        ),
    ]
