# Generated by Django 5.0.3 on 2024-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_userprofile_activities_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
