# Generated by Django 5.0.3 on 2024-04-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_pageview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='url',
        ),
    ]
