# Generated by Django 4.2.7 on 2024-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_pageview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
